### ISSUE TITLE
How can I use “STEP rotates -60 degree”?

### ISSUE THREAD

**Issue by kuangdash** [abbr/ShowPreper#6] opened 2017-06-29 11:18 UTC
Impressjs use negative degrees to represent "turn left", use postive degrees to represent "turn right", but I can't get the correct consequence when I input "-60" which gets "300" in result.

**Comment by kuangdash** [comment] 2017-06-29 14:02
The pull-request before didn't work, so I have changed another part which will causes another problem...

What's more, how can I get the same "rotate preview" like Strut does? When I rotate the slide in overview mode, It can't get "near big far small" effect.

**Comment by abbr** [comment] 2017-06-30 04:06
Whether canonical range is [0,360) or [-180,180) is a matter of choice.

**Comment by kuangdash** [comment] 2017-06-30 08:47
“300 degree” means “turn right 300 degree” while “-60 degree” means “turn left 60 degree”，which are totally different behaviours.

**Comment by kuangdash** [comment] 2017-06-30 09:42
Furthermore, how can I get the same "rotate preview" like Strut does? When I rotate the slide in overview mode (edit mode) , It can't get "near big far small" effect.

**Comment by abbr** [comment] 2017-06-30 17:07
ShowPreper only records final position rather than direction of rotation (at least presently), therefore -60 and 300 makes no difference.

I saw there is a bug when dragging *translate-z* icon on a slide in overview the z value doesn't change. I will fix that. Meanwhile you can type the z value in text box.

**Comment by abbr** [comment] 2017-06-30 22:19
I have merged your request. The code you removed was intended to fix an issue that I couldn't recall anymore. Maybe it's less critical than supporting impressjs rotation direction.
Thanks

**Closed by abbr** 2017-06-30 22:19 UTC
